services:
  - type: web
    name: houston-traffic-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      mkdir -p /data
      chmod 777 /data
      gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: SCRAPE_INTERVAL
        value: 60
      - key: MAX_ALERTS_PER_HOUR
        value: 20
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: INCLUDE_STALLS
        value: true
      - key: RENDER
        value: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
